name: hello-sync
on:
  schedule:
    - cron: '14 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-YG-tsj-Heroku-xray-trojangows-ssws
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync YG-tsj-Heroku-xray-trojangows-ssws
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/YG-tsj/Heroku-xray-trojangows-ssws.git"
          source_branch: "master"
          destination_branch: "hello123"
          github_token: ${{ secrets.PAT }}
